cxx_compiler:                # [win]
  - 'vs2019'                 # [win]
c_compiler:                  # [win]
  - 'vs2019'                 # [win]
vc:                          # [win]
  - 16                       # [win]
CMAKE_GENERATOR:             # [win]
  - 'Visual Studio 16 2019'  # [win]